spring.application.name=template-app
server.error.whitelabel.enabled=true

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/template_app?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:secret}

spring.sql.init.mode=always

# if you don't want to restart mysql on every application restart feel free to remove this
spring.docker.compose.stop.command=down

logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE

spring.mvc.favicon.enabled=false
